[package]
name = "tauri-plugin-launcher"
version = "0.0.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.57"
exclude = ["/examples"]

[dependencies]
tauri = { version = "1.0.0-rc.9" }
